version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - CONFIG_PATH=/app/configs/config.yaml
    networks:
      - app-network

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: file_uploads
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
